### ISSUE TITLE
Options for disabling url rewrite

### ISSUE THREAD

**Issue by alx-xo** [lsirivong/gatsby-plugin-modal-routing#15]
Hey this Gatsby plugin is awesome, thanks for creating it!

Would it be possible to disable the url rewriting? I like the ability to loading a route. But want to pass some props to it when the modal is triggered. If the modal "page" is refreshed or visited without the referring page it will be less useful.

Thank again

**Comment by lsirivong** [comment]
Hey thanks for the kind words!

The support for URLs and the server rendering of the same page content is the main reason I made this plugin.

Maybe using [`react-modal`](reactjs/react-modal) directly would be more appropriate for your use case?

**Comment by alx-xo** [comment]
I was going to use react-modal, but I've decided to use this as an opportunity to better learn React's Context API. Using your concepts as inspiration. Cheers!
