### ISSUE TITLE
shouldCloseOnOverlayClick in props

### ISSUE THREAD

**Issue by darrenlma** [lsirivong/gatsby-plugin-modal-routing#16]
Just implemented and loving the plugin, thank you for your time in creating.

I am just looking to add `shouldCloseOnOverlayClick` to the `modalProps`, however it isn't working for me. Any idea why this could be?

`{
      resolve: 'gatsby-plugin-modal-routing',
      options: {
        modalProps: {
          style: {
            overlay: {
              zIndex: 1001
            },
            content: {
              margin: '0 auto'
            }
          },
          shouldCloseOnOverlayClick: true
        }
      }
    },`

**Comment by lsirivong** [comment]
Hey @discovrbookings thanks for the kind words!

It looks like `shouldCloseOnOverlayClick` also requires support for the `onRequestClose` prop, which would update the `isOpen` value.

I'll try to take a look this week for how to support this, but in the mean time I think one workaround could be to hide react-modal's overlay with CSS, render your own overlay, and handle the click/routing on that component in your app.

**Comment by darrenlma** [comment]
Thanks. I had done as suggested and look forward to hearing from you. Another prop that isn't supported us the `closeTimout`, if you get a moment.

**Comment by johnachastain** [comment]
I have also just implemented your plugin, and have encountered the same concern as mentioned above. I would love to see support for overlay clicks that close the modal.

**Comment by lsirivong** [comment]
@johnachastain thanks for adding your feedback to this. Been a bit busy this last week, hoping to make some time in the next few days to take a look into this.

**Comment by lsirivong** [comment]
Released in v1.0.2

@discovrbookings re: `closeTimeout` support - I don't have an obvious fix for that right now, so I tracked that in a new issue.
