### ISSUE TITLE
use lodash.get instead of lodash to reduce bundle size

### ISSUE THREAD

**Issue by borisirota** [lsirivong/gatsby-plugin-modal-routing#18]
Hi, I see that you are using lodash only for the get functionality.
What do you say about importing only the lodash.get package to decrease unneeded bundle size?

Thanks,
Boris

**Comment by lsirivong** [comment]
Thanks for the suggestion, @borisirota! I'm looking into this now.

**Comment by lsirivong** [comment]
Released in v1.0.1

**Comment by borisirota** [comment]
@lsirivong Thanks!
