### ISSUE TITLE
"Rendering <Context> directly is not supported" error on opening a modal

### ISSUE THREAD

**Issue by mikhail-shishov** [lsirivong/gatsby-plugin-modal-routing#24]
Hi,

I've encountered this issue when I was firing a modal on my website. It doesn't seem to affect anything, but I'm curious why is it there and what can be done to eliminate it. I think that "import { ModalRoutingContext } from 'gatsby-plugin-modal-routing'" line causes it somehow since I don't have the same error on the pages without modals, but I'm not sure about it. I use the latest versions of both plugin and gatsby.

My code for a modal is the default at the time:
```
const ModalExamplePage = () => (
  <ModalRoutingContext>
    {({ modal = true, modalCloseTo = "/" }) => (
      <div>
        {modal ? (
          <Link to="/">
            Close
          </Link>
        ) : (
          <header>
            <h1>
              Website Title
            </h1>
          </header>
        )}
        <h2>Modal Page</h2>
        <Link to="/">Go back to the homepage</Link>
      </div>
    )}
  </ModalRoutingContext>
)
export default ModalExamplePage
```

I can provide you with additional pieces of code if you need any. Thanks!

![Screenshot 2019-08-24 at 14 01 50](https://user-images.githubusercontent.com/26872910/63636423-c16c0300-c677-11e9-8cfb-8b1c5f8bb416.png)

**Comment by lsirivong** [comment]
Hi @mksh-su thanks for the report. I'll try to take a look at this some time this week. In the mean time, if you could share an example repository for me it would definitely help.

**Comment by mikhail-shishov** [comment]
Hey @lsirivong,  
Sorry, but I'm new to Gatsby and I'm not sure how to share the rep privately, and I can't share it on github in public.

**Comment by mduecker** [comment]
@mksh-su 
Change  `<ModalRoutingContext>...</ModalRoutingContext>` to `<ModalRoutingContext.Consumer> ...</ModalRoutingContext.Consumer>` that will fix the error.

**Comment by mikhail-shishov** [comment]
@mduecker,
It really solves the issue! Thanks.

**Comment by nextlevelshit** [comment]
Should we put that fix into `README.md`?

**Comment by lsirivong** [comment]
Fixed up the README, sorry for the confusion and thanks for the help here y'all!
