### ISSUE TITLE
Background scrolls while modal is open

### ISSUE THREAD

**Issue by samabdcom** [lsirivong/gatsby-plugin-modal-routing#45]
Hey @lsirivong ! Thank you for creating this plugin! Using it on my personal project.

I stuck with the issue of modal background scrolling like on your example: 
![2019-12-05 17-53-34 2019-12-05 17_58_08](https://user-images.githubusercontent.com/2075522/70246526-f57fb580-1788-11ea-8d08-2d7fdd8cec5d.gif)

I tried a few options like applying `overflow: hidden` to parent elements, checking if there any `absolute` elements but didn't find a solution.

Do you know what do with that?

Thanks!

**Comment by lsirivong** [comment]
Hey @samabdcom glad it's working out for you.

I'd check in the `react-modal` repo for some suggestions on how to handle this, maybe this issue is a good place to start: https://github.com/reactjs/react-modal/issues/191

**Comment by samabdcom** [comment]
Thank you @lsirivong! Will look into that 👌
