### ISSUE TITLE
Different Result on gatsby develop vs. build

### ISSUE THREAD

**Issue by kpennell** [lsirivong/gatsby-plugin-modal-routing#46]
Hi there - Awesome Plugin here.

My use of it works great on Gatsby build. It sets up a nice modal that hangs over the page and is close-able. Like Instagram, yay!

But on gatsby build + serve, the modal just chills the bottom 20% of the page. Like something isn't working right on build.

In the past.....(recent past) I've had to use gatsby-browser or gatsby-ssr to wrap elements to get them to work right. Stuff breaks otherwise. Could that be the case here?

sandbox: https://codesandbox.io/s/github/kpennell/acrotagsProd/tree/master/?fontsize=14&hidenavigation=1&theme=dark

Maybe because I'm using a component with a graphql query at the bottom?

**Comment by kpennell** [comment]
in action: https://acrotags.com/

**Comment by lsirivong** [comment]
Strange! Not sure why the styles would work in development but not after building. I'm suspicious of this plugin you have configured: `gatsby-plugin-purgecss`. I'm guessing it's not recognizing that the React modal styles that are configured in gatsby-config.js

**Comment by anantoghosh** [comment]
Yup, `gatsby-plugin-purgecss` will not find selectors defined in `gatsby-config.js`.
Whitelist the selectors ReactModal__Overlay, ReactModal__Content https://github.com/anantoghosh/gatsby-plugin-purgecss#1-whitelist-the-selector-using-the-whitelist-option-in-gatsby-configjs
or to whitelist all selectors starting with ReactModal https://github.com/anantoghosh/gatsby-plugin-purgecss#3--use-regex-pattern-to-exclude-many-selectors

**Comment by kpennell** [comment]
@anantoghosh Thx for the response. That was it. I had tried removing it before but must have been running on cache or something like that
